FROM debian:bullseye AS builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    build-essential \
    libboost-system-dev \
    libboost-program-options-dev \
    libboost-filesystem-dev \
    libboost-date-time-dev \
    libboost-chrono-dev \
    libssl-dev \
    zlib1g-dev \
    ca-certificates

WORKDIR /app
RUN git clone --recursive https://github.com/purplei2p/i2pd-tools .

RUN make LDFLAGS="-static"

FROM scratch
COPY --from=builder /app/vain /
