name: Generate Vanity Address

on:
  workflow_dispatch:
    inputs:
      prefix:
        description: 'The desired prefix for the vanity address (a-z, 2-7)'
        required: true
        default: 'example'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Validate user input prefix
        run: |
          if [[ ! "${{ github.event.inputs.prefix }}" =~ ^[a-z2-7]+$ ]]; then
            echo "Error: Prefix must only contain Base32 characters (a-z, 2-7)."
            exit 1
          fi

      - name: Install Runtime Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libboost-system1.74.0 \
            libboost-program-options1.74.0 \
            libboost-filesystem1.74.0 \
            libboost-date-time1.74.0 \
            libboost-chrono1.74.0 \
            libssl1.1 \
            zlib1g

      - name: Download and extract pre-compiled binary
        run: |
          curl -sL https://github.com/${{ github.repository }}/releases/latest/download/vain-linux-amd64.tar.gz -o vain.tar.gz
          tar -xzvf vain.tar.gz
          chmod +x ./vain
        
      - name: Generate Vanity Address
        run: ./vain ${{ github.event.inputs.prefix }} --output ./private.dat

      - name: Upload private.dat as artifact
        uses: actions/upload-artifact@v4
        with:
          name: private-key-${{ github.event.inputs.prefix }}
          path: ./private.dat
