name: Generate Vanity Address

on:
  workflow_dispatch:
    inputs:
      prefix:
        description: 'The desired prefix for the vanity address (a-z, 2-7)'
        required: true
        default: 'example'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Validate user input prefix
        run: |
          if [[ ! "${{ github.event.inputs.prefix }}" =~ ^[a-z2-7]+$ ]]; then
            echo "Error: Prefix must only contain Base32 characters (a-z, 2-7)."
            exit 1
          fi

      - name: Download and extract pre-compiled binary
        run: |
          # Download the specific release asset
          curl -sL https://github.com/${{ github.repository }}/releases/download/v1.0.1/vain-linux-amd64.tar.gz -o vain.tar.gz
          # Extract the binary
          tar -xzvf vain.tar.gz
          # Make it executable
          chmod +x ./vain
        
      - name: Generate Vanity Address
        run: ./vain ${{ github.event.inputs.prefix }} --output ./private.dat

      - name: Upload private.dat as artifact
        uses: actions/upload-artifact@v4
        with:
          name: private-key-${{ github.event.inputs.prefix }}
          path: ./private.dat
