name: Build and Release AMD64 Binary

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build for linux/amd64
        run: |
          docker buildx build \
            -f Dockerfile.build \
            -o ./dist \
            .
      
      - name: Package binary
        run: |
          cd ./dist && tar -czvf ../vain-linux-amd64.tar.gz vain

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./vain-linux-amd64.tar.gz
